### ISSUE TITLE
Merge antlr4-c3 and this project

### ISSUE THREAD

**Issue by mike-lischke** [ftomassetti/antlr4-c3-kotlin#1]
Hi, I just [got a Java port](https://github.com/mike-lischke/antlr4-c3/pull/8) of the c3 engine and merged it into a `ports/` subfolder. I also plan to add my C++ port there, so I wonder if you would be willing to have your Kotlin port added there too. This would effectively be a merge of our 2 projects.

If you agree you could normally fork antlr4-c3, add your port and send me a pull request. Just a suggestion ...

**Comment by ftomassetti** [comment]
I would be happy to merge it, but having both a Java and a Kotlin port could bring confusion because Java developers can use Kotlin code and viceversa. What do you think? Should we pick one and discontinue the other one?

**Comment by mike-lischke** [comment]
Well, tbh I'm not sure. For my outside view Java and Kotlin are 2 different languages, so IMO it's worth to keep both ports. A dev who wants to code in Java wouldn't look for the Kotlin port as (s)he wouldn't know it's related to Java.

**Comment by ftomassetti** [comment]
I would expect the majority of Java developers to know that Kotlin is compatible and all Kotlin developers to know that. We could also underline it in the documentation. For this reason I still think it could fractionate the community having both a Java and a Kotlin port and it would also be a duplication of effort. If we really want to have both we could build a little Kotlin facade in front of the Java implementation to make it more "kotlinesque" but the benefits would be minimal.

All in all I think that it would make more sense for me to contribute and help the Java port.

**Comment by mike-lischke** [comment]
OK, makes sense. Thank you.
